### ISSUE TITLE
Requirements suggestion for Navigating Using GPS Localization

### ISSUE THREAD

**Issue by jimdinunzio** [ros-navigation/docs.nav2.org#588]
Hi Steve or others,
After some hours of grief figuring out myself I would recommend adding this to the requirements of the GPS tutorial. BTW, I just jumped directly to this tutorial without starting with turtlebot3 so I didn't have it installed.

Navigating Using GPS Localization
Additional Requirements:

- sudo apt install ros-$ROS_DISTRO-gazebo-*
- - to get the correct gazebo installation with the necessary plugin. NOT sudo apt install gazebo - I don't know what that does but it is bad.
- sudo apt install ros-$ROS_DISTRO_turtlebot3-gazebo
- - without this gazebo takes forever to launch and it cannot find the mesh file for turtle3-waffle
-

**Comment by SteveMacenski** [comment]
Done, thanks! https://github.com/ros-navigation/docs.nav2.org/blob/master/tutorials/docs/navigation2_with_gps.rst
