### ISSUE TITLE
Word spelling mistake

### ISSUE THREAD

**Issue by zhukao** [ros-navigation/docs.nav2.org#622]
There is a word spelling mistake in chapter [rotate-in-place-behavior](https://docs.nav2.org/tuning/index.html#rotate-in-place-behavior):

> This behavior is most optimially for:

optimially => optimally

**Comment by SteveMacenski** [comment]
Fixed in https://github.com/ros-navigation/docs.nav2.org/commit/1e7510d7a1327afb33916b7f3afee7561c595361

In general, for things like this, you can just submit a PR and I'll pretty much just immediately merge it :-) 

Thanks for the note!
